/*
 * generated by Xtext 2.20.0
 */
package org.iot.devicefactory


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CommonStandaloneSetup extends CommonStandaloneSetupGenerated {

	def static void doSetup() {
		new CommonStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
