/*
 * generated by Xtext 2.20.0
 */
package org.iot.devicefactory


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DeviceFactoryStandaloneSetup extends DeviceFactoryStandaloneSetupGenerated {

	def static void doSetup() {
		new DeviceFactoryStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
