package org.iot.devicefactory.validation

interface DeviceFactoryIssueCodes {
	val ISSUE_PREFIX = "org.iot.devicefactory.deviceFactory."
	
	val MISSING_CHANNEL = ISSUE_PREFIX + "MISSING_CHANNEL"
	val MISSING_DEVICE = ISSUE_PREFIX + "MISSING_DEVICE"
	val AMBIGUOUS_FOG = ISSUE_PREFIX + "AMBIGUOUS_FOG"
	val MISSING_CLOUD = ISSUE_PREFIX + "MISSING_CLOUD"
	val AMBIGUOUS_CLOUD = ISSUE_PREFIX + "AMBIGUOUS_CLOUD"
	
	val SUPERFLUOUS_LIBRARY = ISSUE_PREFIX + "SUPERFLUOUS_LIBRARY"
	val UNSUPPORTED_LANGUAGE = ISSUE_PREFIX + "UNSUPPORTED_LANGUAGE"
	val INCORRECT_OUT_TYPE = ISSUE_PREFIX + "INCORRECT_OUT_TYPE"
	
	val ILLEGAL_OVERRIDE = ISSUE_PREFIX + "ILLEGAL_OVERRIDE"
	val MISSING_OVERRIDE = ISSUE_PREFIX + "MISSING_OVERRIDE"
	
	val DUPLICATE_CHANNEL = ISSUE_PREFIX + "DUPLICATE_CHANNEL"
	val DUPLICATE_DEVICE = ISSUE_PREFIX + "DUPLICATE_DEVICE"
	val DUPLICATE_SENSOR = ISSUE_PREFIX + "DUPLICATE_SENSOR"
	val DUPLICATE_DATA = ISSUE_PREFIX + "DUPLICATE_DATA"
}
