/*
 * generated by Xtext 2.20.0
 */
package org.iot.devicefactory.validation

import java.util.HashSet
import org.eclipse.xtext.validation.Check
import org.iot.devicefactory.deviceLibrary.Board
import org.iot.devicefactory.deviceLibrary.DeviceLibraryPackage.Literals

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DeviceLibraryValidator extends AbstractDeviceLibraryValidator {
	
	public static val INHERITANCE_CYCLE = "org.iot.devicefactory.deviceLibrary.INHERITANCE_CYCLE"
	
	@Check
	def validateNoInheritanceCycles(Board board) {
		val known = new HashSet<Board>()
		var current = board
		while (current !== null) {
			if (known.contains(current)) {
				error("Inheritance cycles are not allowed", Literals.BOARD__PARENT, INHERITANCE_CYCLE)
				return
			}
			
			known.add(current)
			current = current.parent
		}
	}
}
